name: Build on macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Install Homebrew and Conan
      - name: Install Conan
        run: |
          brew install conan

      # 3. Detect Conan profile
      - name: Detect Conan profile
        run: conan profile detect --force

      # 4. Install dependencies with Conan
      - name: Conan install
        run: conan install . --output-folder=build --build=missing

      # 5. Configure project with CMake preset
      - name: CMake configure
        run: cmake --preset conan-release

      # 6. Build project with CMake preset
      - name: CMake build
        run: cmake --build --preset conan-release